spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  redis:
    host: localhost
    port: 6379

cloud:
  aws:
    s3:
      bucket: day-film-bucket
      filePath: ${cloud.aws.s3.filePath}
    credentials:
      instanceProfile: true
      accessKey: ${cloud.aws.credentials.accessKey}
      secretKey: ${cloud.aws.credentials.secretKey}
    region:
      static: ap-northeast-2
    stack:
      auto: false

businessApi:
  serviceKey: ${businessApi.serviceKey}

secure:
  jwt:
    secretKey: ${secure.jwt.secretKey}
    issuer: ${secure.jwt.issuer}
  RSA:
    privateKey: ${secure.RSA.privateKey}
    publicKey: ${secure.RSA.publicKey}